### ISSUE TITLE
umare V1.6.5 SID to RID return type is uint32 and its not compatible with FIM.

### ISSUE THREAD

**Issue by Manjunath-hk1** [lithnet/umare#13]
Hi Ryan,

Can the return type of SIDToRID be adjusted to int32.

We see conversion error in  #FIM.

System.FormatException: The object of type 'UInt32' cannot be converted to long/string
   at Lithnet.MetadirectoryServices.TypeConverter.ConvertToBinary(Object obj)
   at Lithnet.MetadirectoryServices.TypeConverter.ConvertData[T](Object obj)
   at Lithnet.Umare.MAExtensionObject.SetAttributeValue(Object attributeValue, Attrib attribute)
   at Lithnet.Umare.MAExtensionObject.Microsoft.MetadirectoryServices.IMASynchronization.MapAttributesForImport(String flowRuleName, CSEntry csentry, MVEntry mventry)

https://github.com/lithnet/umare/releases/tag/v1.6.5

Thanks,
Manju

**Comment by ryannewington** [comment]
Hi Manju,

what's the type of the metaverse attribute you are flowing to?

**Comment by ryannewington** [comment]
Try this one https://github.com/lithnet/umare/releases/tag/v2.0.4, but make sure the metaverse attribute being populated is an integer in FIM

**Comment by Manjunath-hk1** [comment]
Tried with both number and string when the return type was "uint", same error

**Comment by Manjunath-hk1** [comment]
Looks good now, Thanks for helping so quick.
